blank_issues_enabled: false
contact_links:
  - name: 前往讨论区 (💬 Discussions)
    url: https://github.com/axuitomo/CFST-GUI/discussions
    about: Issues 仅用于对 CFST-GUI 本身的反馈问题和功能建议，其他话题请到 Discussions 发帖讨论。
