// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appcore} from '../models';
import {app} from '../models';

export function CheckForUpdates(arg1:Record<string, any>):Promise<appcore.CommandResult>;

export function DownloadAndInstallUpdate(arg1:Record<string, any>):Promise<appcore.CommandResult>;

export function GetAppInfo():Promise<appcore.CommandResult>;

export function GetHealth():Promise<app.HealthResult>;

export function HideMainWindow():Promise<appcore.CommandResult>;

export function Invoke(arg1:string,arg2:string):Promise<string>;

export function OpenLogDirectory(arg1:Record<string, any>):Promise<appcore.CommandResult>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenReleasePage():Promise<appcore.CommandResult>;

export function QuitApplication():Promise<appcore.CommandResult>;

export function SelectPath(arg1:Record<string, any>):Promise<appcore.CommandResult>;

export function ShowMainWindow():Promise<appcore.CommandResult>;
