// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['app']['App']['CheckForUpdates'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['app']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetHealth() {
  return window['go']['app']['App']['GetHealth']();
}

export function HideMainWindow() {
  return window['go']['app']['App']['HideMainWindow']();
}

export function Invoke(arg1, arg2) {
  return window['go']['app']['App']['Invoke'](arg1, arg2);
}

export function OpenLogDirectory(arg1) {
  return window['go']['app']['App']['OpenLogDirectory'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['app']['App']['OpenPath'](arg1);
}

export function OpenReleasePage() {
  return window['go']['app']['App']['OpenReleasePage']();
}

export function QuitApplication() {
  return window['go']['app']['App']['QuitApplication']();
}

export function SelectPath(arg1) {
  return window['go']['app']['App']['SelectPath'](arg1);
}

export function ShowMainWindow() {
  return window['go']['app']['App']['ShowMainWindow']();
}
